### ISSUE TITLE
Quality of life: ControlNet layer mask order

### ISSUE THREAD

**Issue by Miraihi** [DrCyanide/cyanic-sd-krita#14]
Outside of my already stated mild dissatisfaction about the generated layer clutter, there's one more significant annoyance.

Every "result" group of the controlnet plces the mask on top of the actual generated picture. So after the generation you have to delete the mask or make it invisible to see the result. I think the mask should be invisible by default, or be placed under the generated layer.

**Comment by DrCyanide** [comment]
I've been having a similar issue with ControlNet previews being added to the results. IMO it's pretty dumb that both masks and temporary preprocessed images are added to the results. I'm leaning towards automatically deleting them from the results, but I need to be smart about it so I don't accidentally delete real results when batch operations are added.

----

FYI, in general my priority lists looks something like this:

1. Fix bugs that are either reported or found on my own
2. Add functionality (RemBG, Face Restore, Batches, HiRes Fix, etc.)
3. UI fixes (ControlNet can have controls squished to unusable levels - but it can be worked around or ignored, so it's lower than other fixes)
4. Quality of Life improvements (Auto HR Fix, Better folder management, option to hide settings on the different pages, settings presets, per-file prompts, etc)

Of course this is subject to change. Some QoL changes will get bumped up in priority (like picking what UIs have Shared Prompts), while some functionality might get bumped down (Roop/ReActor are currently in that boat). But I bring it up because I don't want you to think you're shouting into the void with these suggestions. You've been an amazing help in developing this plugin, and I highly value your feedback.

**Comment by Miraihi** [comment]
@DrCyanide I agree with the priorities. Also it's nothing, you've made an amazing plugin and I'm happy to be of any help. It took other developer months to add a basic controlnet functionality, only for it to break once and never get fixed.
I hope Cyanic-sd gets more recognition it truly deserves.

**Comment by DrCyanide** [comment]
These "extra" images/layers should be deleted from the results now. I'm figuring out how many results there should be by multiplying the batch count by the number of iterations, then trimming out any results after that. It's possible that there's some use cases that I missed in other workflows, but for ControlNet it should be better.

(This was a case where the annoyance was too great, I was dealing with related code anyway, and the fix was pretty simple to code, so it got bumped up)
