### ISSUE TITLE
Feature request: Auto-updating inpainting masks

### ISSUE THREAD

**Issue by Miraihi** [DrCyanide/cyanic-sd-krita#15]
The title. While you're aware of this request, it won't hurt to keep things organized.

It gets a bit annoying when you complete a set of generations on one portion of the image and shift to the next, but then generate over the old mask upon hitting the "generate" just because you've forgot to manually update the mask.

I think you can go about that by automatically generating a layer named "Inpaint mask" upon shifting to the "inpainting" tab, and everything drawn on this layer will count as a mask ([Photoshop](https://github.com/AbdullahAlfaraj/Auto-Photoshop-StableDiffusion-Plugin) extension does that. Also it constantly reminds you to select the region to work on so you can never forget.)

**Comment by DrCyanide** [comment]
I'm brainstorming how to implement this, and I want to run some possible options past you.

Right now if you don't manually use the "Use Selection"/"Use Layer"/"Use Canvas" buttons before you click "Generate" the first time, the program assumes you want to Use Canvas and that your active layer is your mask. I think it makes sense to keep that as the default behavior, rather than creating a new layer automatically for the user (which could be irritating if someone accidentally selected Inpaint)

What I'm considering adding (as checkbox options):

* **"Update mask before generating"** - I'll save the ID of the mask layer (either the auto selected or manually selected) and refresh the mask before sending it off to Inpaint. This is the bare minimum that would fulfill this feature request.
* **"Add results below mask"** - While adding RemBG, I added code to move a layer below another layer. I think this would help keep Inpainting more organized, and make it easier to refine the mask to fit the new generation.
* **"Hide mask on generate"** - Toggle off the visibility of the mask after the "Generate" button is clicked. When combined with the "Add results below mask" option it would allow you to quickly see the areas changed.

Do these options sound useful? Is there any other option that would make sense to add?

**Comment by Miraihi** [comment]
Right now as it's defaulting to the selection when on Inpaint tab it's already making a huge difference in usability. Updating the mask when I hit "Generate" is about what I expect intuitively, as it removes one excessive action I otherwise have to perform every single time.

Adding results below mask sounds nice, hiding mask is also useful (Other plugins do exactly that).

**Comment by DrCyanide** [comment]
Pushed - Have fun! Thanks for all your help improving this plugin.
