### ISSUE TITLE
Feature Requests: Refiner

### ISSUE THREAD

**Issue by irldoggo** [DrCyanide/cyanic-sd-krita#21]
So far I am loving this plugin, it handles my workflow almost flawlessly. I was hoping you would be able to add the refiner functionality. I like to use multiple checkpoints during a generation to push the style in a certain direction, would it be possible to add the ability select a refiner checkpoint and set which step it activates?

Thanks much!

**Comment by DrCyanide** [comment]
The A1111 API supports `refiner_checkpoint` and `refiner_switch_at`, so it should be possible to add.

**Comment by DrCyanide** [comment]
I've added the A1111 version of refiners. Turns out A1111 and SD.Next differ in how they handle Refiners - both in their UI and in their APIs - which makes it a bit annoying to implement fully. I can't even find a UI option for refiners in SD.Next (only a Settings menu option), so it's going to take a lot more trial and error to get that one working.

**Comment by irldoggo** [comment]
Appreciate it, I am using A1111, so this is perfect for me.

**Comment by DrCyanide** [comment]
I've attempted to get Refiners working in SD.Next, but I'm having issues getting them to work in the WebUI on my machine. After following the advice of Vlad on his discord and in https://github.com/vladmandic/automatic/issues/2521 I think I've got the API call correct, so I'm going to mark this as complete and assume that on someone else's computer it would work.
