### ISSUE TITLE
Turning on Save images on host will squish the other image in batch generation

### ISSUE THREAD

**Issue by rexelbartolome** [DrCyanide/cyanic-sd-krita#25]
Not sure how to describe it but this setting makes the "fitting" of the other generation incorrectly squished

https://github.com/DrCyanide/cyanic-sd-krita/assets/88552647/e81c29a7-73c5-4add-b066-a78193a8ce28

[log-squished-dragon.json](https://github.com/DrCyanide/cyanic-sd-krita/files/13440263/log-squished-dragon.json)

**Comment by DrCyanide** [comment]
*sigh* I know what's going on, I just need to figure out a way to fix it.

You're running with a Batch Size of 2. The squished image is the grid of results that normally shows up in the Web UI, being squeezed into the width specified in your selection. It's not something you asked for, but it's in the results anyway.

Similarly, ControlNet returns the results of it's preprocessor as an extra image that just clutters up Krita. I tackled those extra images first - by deleting any image from the results after Batch Size * Batch Count.

The problem here is that the Grids come before the desired images, while ControlNet preprocessed comes after. I can't just blindly delete from one end of the results or the other, I have to figure out which images are the junk and delete only those...

**Comment by DrCyanide** [comment]
I think I have a fix for this now. Try pulling and see if that works better.
